//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team08ASportsFacilityBooking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SA46Team08ADatabaseEntities : DbContext
    {
        public SA46Team08ADatabaseEntities()
            : base("name=SA46Team08ADatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Member> Members { get; set; }
    
        public virtual ObjectResult<bookings_tomorrow_onwards_Result> bookings_tomorrow_onwards()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bookings_tomorrow_onwards_Result>("bookings_tomorrow_onwards");
        }
    }
}
